bus:
  path: localhost:10001
command: svc/eva-generic-db-service
react_to_fail: true
timeout:
  startup: 360.0
user: nobody
workers: 1
config:
  db: "postgres://eva-user:12345@127.0.0.1:5432/eva-db"
  unix: false
  ssl: false
  columns:
    - name: id
      type: BIGSERIAL
      primary_key: true
    - name: mp
      type: TEXT
      not_null: true
    - name: code_rc
      type: TEXT
      not_null: true
      unique: true
    - name: name
      type: TEXT
      not_null: true
    - name: multiplicity
      type: INTEGER
      default: 1
      not_null: true
    - name: packagingType
      type: TEXT
    - name: barcode
      type: TEXT
      unique: true
      not_null: true
    - name: subject
      type: TEXT
      not_null: true
