bus:
  path: localhost:10001
command: svc/eva-generic-db-service
react_to_fail: true
timeout:
  startup: 360.0
user: nobody
workers: 1
config:
  db: "postgres://eva-user:12345@127.0.0.1:5432/eva-db"
  unix: false
  ssl: false
  columns:
    - name: "id"
      primary_key: true
      type: "BIGSERIAL"
    - name: "mp"
      not_null: true
      type: "TEXT"
    - name: "code_rc"
      not_null: true
      type: "INTEGER"
      unique: true
    - name: "name"
      not_null: true
      type: "TEXT"
    - default: 1
      name: "multiplicity"
      not_null: true
      type: "INTEGER"
    - name: "packaging_type"
      type: "TEXT"
    - name: "barcode"
      not_null: true
      type: "TEXT"
      unique: true
    - name: "subject"
      not_null: true
      type: "TEXT"
    - name: "created_at"
      type: "TIMESTAMPTZ"
      not_null: true
      default: "now()"
